apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horizex-api
  template:
    metadata:
      labels:
        app: horizex-api
    spec:
      containers:
        - name: horizex-api
          image: horizex-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: horizex-service
spec:
  type: NodePort
  selector:
    app: horizex-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # expose on localhost:30080
