spring:
  application:
    name: horizex

logging:
  level:
    root: WARN
    com.horizex: DEBUG
    org.springframework: WARN
    org.flywaydb: WARN

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
